// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCaIT2l3mBR2ihObNfWSKGc1N0n-1dyd8E',
    appId: '1:824249688083:web:your-web-app-id',
    messagingSenderId: '824249688083',
    projectId: 'foodbank1-49283',
    authDomain: 'foodbank1-49283.firebaseapp.com',
    storageBucket: 'foodbank1-49283.appspot.com',
    measurementId: 'your-measurement-id',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaIT2l3mBR2ihObNfWSKGc1N0n-1dyd8E',
    appId: '1:824249688083:android:fada2282200443395b1fe6',
    messagingSenderId: '824249688083',
    projectId: 'foodbank1-49283',
    storageBucket: 'foodbank1-49283.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaIT2l3mBR2ihObNfWSKGc1N0n-1dyd8E',
    appId: '1:824249688083:ios:your-ios-app-id',
    messagingSenderId: '824249688083',
    projectId: 'foodbank1-49283',
    storageBucket: 'foodbank1-49283.appspot.com',
    iosBundleId: 'com.example.ase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCaIT2l3mBR2ihObNfWSKGc1N0n-1dyd8E',
    appId: '1:824249688083:macos:your-macos-app-id',
    messagingSenderId: '824249688083',
    projectId: 'foodbank1-49283',
    storageBucket: 'foodbank1-49283.appspot.com',
    iosBundleId: 'com.example.ase',
  );
}
